basicConstraints=CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName=@my_subject_alt_names
subjectKeyIdentifier = hash

[ my_subject_alt_names ]
DNS.1 = www.myproj.com
DNS.2 = www.myproj2.com
DNS.3 = www3.myproj.com
DNS.4 = www4.myproj2.com
